import { Recipe } from '../types';

export const DUMMY_RECIPES: Recipe[] = [
  {
    id: 'dummy_1',
    name: 'Spaghetti Carbonara',
    description: 'A classic Italian pasta dish made with eggs, cheese, pancetta, and pepper.',
    category: 'main-course',
    prepTime: 15,
    cookTime: 15,
    totalTime: 30,
    servings: 4,
    defaultServings: 4,
    difficulty: 'medium',
    ingredients: [
      { id: '1', name: 'Spaghetti', amount: 400, unit: 'g' },
      { id: '2', name: 'Pancetta', amount: 150, unit: 'g' },
      { id: '3', name: 'Eggs', amount: 4, unit: 'large' },
      { id: '4', name: 'Pecorino Romano', amount: 100, unit: 'g' },
      { id: '5', name: 'Black Pepper', amount: 1, unit: 'tsp' },
    ],
    steps: [
      'Boil pasta in salted water.',
      'Fry pancetta until crisp.',
      'Whisk eggs and cheese together.',
      'Combine pasta and pancetta, remove from heat.',
      'Stir in egg mixture quickly to create sauce.',
      'Season with pepper.'
    ],
    tags: ['Italian', 'Pasta', 'Quick'],
    isFavorite: true,
    rating: 5,
    reviewCount: 120,
    createdAt: new Date('2023-01-01'),
    updatedAt: new Date('2023-01-02'),
    userId: 'user_1',
    isPublic: true,
  },
  {
    id: 'dummy_2',
    name: 'Avocado Toast',
    description: 'Simple and healthy breakfast option with poached egg.',
    category: 'breakfast',
    prepTime: 5,
    cookTime: 5,
    totalTime: 10,
    servings: 1,
    defaultServings: 1,
    difficulty: 'easy',
    ingredients: [
      { id: '1', name: 'Bread', amount: 1, unit: 'slice' },
      { id: '2', name: 'Avocado', amount: 0.5, unit: 'whole' },
      { id: '3', name: 'Egg', amount: 1, unit: 'large' },
      { id: '4', name: 'Chili Flakes', amount: 1, unit: 'pinch' },
    ],
    steps: [
      'Toast the bread.',
      'Mash avocado and spread on toast.',
      'Poach egg and place on top.',
      'Sprinkle with chili flakes.'
    ],
    tags: ['Healthy', 'Breakfast', 'Vegetarian'],
    isFavorite: false,
    rating: 4.5,
    reviewCount: 45,
    createdAt: new Date('2023-02-15'),
    updatedAt: new Date('2023-02-15'),
    userId: 'user_1',
    isPublic: true,
  },
  {
    id: 'dummy_3',
    name: 'Chocolate Lava Cake',
    description: 'Decadent chocolate dessert with a gooey center.',
    category: 'dessert',
    prepTime: 20,
    cookTime: 15,
    totalTime: 35,
    servings: 2,
    defaultServings: 2,
    difficulty: 'hard',
    ingredients: [
      { id: '1', name: 'Dark Chocolate', amount: 100, unit: 'g' },
      { id: '2', name: 'Butter', amount: 100, unit: 'g' },
      { id: '3', name: 'Sugar', amount: 100, unit: 'g' },
      { id: '4', name: 'Eggs', amount: 2, unit: 'large' },
      { id: '5', name: 'Flour', amount: 30, unit: 'g' },
    ],
    steps: [
      'Melt chocolate and butter.',
      'Whisk sugar and eggs.',
      'Combine mixtures and fold in flour.',
      'Pour into molds.',
      'Bake at 200°C for 12-15 minutes.'
    ],
    tags: ['Dessert', 'Chocolate', 'Baking'],
    isFavorite: true,
    rating: 4.8,
    reviewCount: 89,
    createdAt: new Date('2023-03-10'),
    updatedAt: new Date('2023-03-10'),
    userId: 'user_1',
    isPublic: true,
  },
  {
    id: 'dummy_4',
    name: 'Caesar Salad',
    description: 'Crisp romaine lettuce with creamy dressing and croutons.',
    category: 'salad',
    prepTime: 20,
    cookTime: 0,
    totalTime: 20,
    servings: 2,
    defaultServings: 2,
    difficulty: 'medium',
    ingredients: [
      { id: '1', name: 'Romaine Lettuce', amount: 1, unit: 'head' },
      { id: '2', name: 'Croutons', amount: 50, unit: 'g' },
      { id: '3', name: 'Parmesan', amount: 30, unit: 'g' },
      { id: '4', name: 'Caesar Dressing', amount: 50, unit: 'ml' },
    ],
    steps: [
      'Wash and chop lettuce.',
      'Toss with dressing.',
      'Top with croutons and parmesan.'
    ],
    tags: ['Salad', 'Healthy', 'Classic'],
    isFavorite: false,
    rating: 4.2,
    reviewCount: 30,
    createdAt: new Date('2023-04-05'),
    updatedAt: new Date('2023-04-05'),
    userId: 'user_1',
    isPublic: true,
  },
  {
    id: 'dummy_5',
    name: 'Berry Smoothie',
    description: 'Refreshing smoothie packed with antioxidants.',
    category: 'drink',
    prepTime: 5,
    cookTime: 0,
    totalTime: 5,
    servings: 1,
    defaultServings: 1,
    difficulty: 'easy',
    ingredients: [
      { id: '1', name: 'Mixed Berries', amount: 150, unit: 'g' },
      { id: '2', name: 'Banana', amount: 1, unit: 'whole' },
      { id: '3', name: 'Yogurt', amount: 100, unit: 'g' },
      { id: '4', name: 'Milk', amount: 100, unit: 'ml' },
    ],
    steps: [
      'Place all ingredients in blender.',
      'Blend until smooth.',
      'Serve immediately.'
    ],
    tags: ['Drink', 'Smoothie', 'Fruit'],
    isFavorite: false,
    rating: 4.6,
    reviewCount: 15,
    createdAt: new Date('2023-05-20'),
    updatedAt: new Date('2023-05-20'),
    userId: 'user_1',
    isPublic: true,
  }
];
